name: ML CI - Fase 1
on: workflow_dispatch
jobs: 
  validate-ml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        user: actions/setup-python@v5

      - name: Install dependecies
        run: |
          pip install -r requirements.txt
      - name: Run training simulation
        run: |
          python src/train.py
